version: '3.8'

services:
  shopmanagerclient:
    image: shopmanagerclient
    build:
      context: .
      dockerfile: ShopManager.Client/Dockerfile
    ports:
      - "3000:80"
    networks:
      - proxynet
  shopmanagerweb:
    image: shopmanagerweb
    build:
      context: .
      dockerfile: ShopManager.Web/Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Host=shopmanagerpostgres;Port=5432;Database=shopmanager;Username=postgres;Password=postgres
    ports:
      - "8000:8080"
    networks:
      - proxynet
  shopmanagerpostgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopmanager
    ports:
      - "5432:5432"
    networks:
      - proxynet
  shopmanagerpgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@senti.dev
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"
    networks:
      - proxynet
networks:
  proxynet:
    name: custom_network